import pytest

from soundmind.playlist_m3u8_import import parse_m3u8

VALID = """#EXTM3U
#EXTINF:12,Hero — Composer
file:///music/a.mp3
#EXTINF:-1,Night
file:///music/b.mp3
"""


def test_parse_m3u8_resolves_catalog_uris_in_order() -> None:
    imported = parse_m3u8(
        VALID,
        {
            "file:///music/b.mp3": "track-b",
            "file:///music/a.mp3": "track-a",
        },
    )

    assert [
        (item.track_id, item.sequence_score, item.base_score)
        for item in imported.items
    ] == [
        ("track-a", 0.0, 0.0),
        ("track-b", 0.0, 0.0),
    ]


@pytest.mark.parametrize(
    ("text", "message"),
    [
        (
            "#EXTINF:12,Missing header\nfile:///music/a.mp3\n",
            "must start with #EXTM3U",
        ),
        (
            "#EXTM3U\n#EXTINF:bad,Track\nfile:///music/a.mp3\n",
            "duration must be numeric",
        ),
        (
            "#EXTM3U\n#EXTINF:12,Track\nhttps://example.com/a.mp3\n",
            "not a local file URI",
        ),
        (
            "#EXTM3U\n#EXTINF:12,Track\nfile:///music/missing.mp3\n",
            "source not found in catalog",
        ),
        (
            "#EXTM3U\n#EXTINF:12,Track\nfile:///music/a.mp3\n#EXTINF:12,Track\nfile:///music/a.mp3\n",
            "duplicate M3U8 source URI",
        ),
        (
            "#EXTM3U\n#EXTINF:12,Track\n",
            "missing a source URI",
        ),
    ],
)
def test_parse_m3u8_rejects_invalid_documents(text: str, message: str) -> None:
    with pytest.raises(ValueError, match=message):
        parse_m3u8(text, {"file:///music/a.mp3": "track-a"})


def test_parse_m3u8_rejects_source_without_extinf() -> None:
    with pytest.raises(ValueError, match="missing a preceding #EXTINF"):
        parse_m3u8(
            "#EXTM3U\nfile:///music/a.mp3\n",
            {"file:///music/a.mp3": "track-a"},
        )


def test_parse_m3u8_ignores_non_extinf_comments() -> None:
    imported = parse_m3u8(
        "#EXTM3U\n# generated by player\n#EXTINF:1,A\nfile:///music/a.mp3\n",
        {"file:///music/a.mp3": "track-a"},
    )

    assert tuple(item.track_id for item in imported.items) == ("track-a",)


def test_parse_m3u8_handles_empty_playlist() -> None:
    assert parse_m3u8("#EXTM3U\n", {}).items == ()


def test_parse_m3u8_rejects_consecutive_extinf() -> None:
    text = "#EXTM3U\n#EXTINF:1,A\n#EXTINF:2,B\nfile:///music/a.mp3\n"
    with pytest.raises(ValueError, match="consecutive #EXTINF"):
        parse_m3u8(text, {"file:///music/a.mp3": "track-a"})


def test_parse_m3u8_rejects_extinf_without_label() -> None:
    text = "#EXTM3U\n#EXTINF:1\nfile:///music/a.mp3\n"
    with pytest.raises(ValueError, match="#EXTINF entry must contain a label"):
        parse_m3u8(text, {"file:///music/a.mp3": "track-a"})


def test_parse_m3u8_rejects_duplicate_catalog_track_id() -> None:
    text = (
        "#EXTM3U\n"
        "#EXTINF:1,A\n"
        "file:///music/a.mp3\n"
        "#EXTINF:1,B\n"
        "file:///music/b.mp3\n"
    )
    with pytest.raises(ValueError, match="duplicate catalog track ID"):
        parse_m3u8(
            text,
            {
                "file:///music/a.mp3": "track-a",
                "file:///music/b.mp3": "track-a",
            },
        )
